server:
  port: 8082

spring:
  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_WRITE_URL}
      username: ${DB_WRITE_USERNAME}
      password: ${DB_PASSWORD}
      maximum-pool-size: 20
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_READ_URL}
      username: ${DB_READ_USERNAME}
      password: ${DB_PASSWORD}
      maximum-pool-size: 10

  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

#AWS Bedrock
aws:
  bedrock:
    sonnet:
      model: anthropic.claude-3-5-sonnet-20240620-v1:0
      arn: arn:aws:bedrock:region:account-id:inference-profile/inference-profile-id
    stablediffusion:
      model: stability.stable-image-core-v1:1

  s3:
    bucket: moai-bucket
